name: Build and Deploy to Cloud Run

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud credentials
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/salus-repo/salus-api:latest .

      - name: Push Docker image
        run: |
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/salus-repo/salus-api:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy salus-mvp \
            --image=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/salus-repo/salus-api:latest \
            --region=us-central1 \
            --platform=managed \
            --allow-unauthenticated
            
